//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInterview.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class empinterviewEntities1 : DbContext
    {
        public empinterviewEntities1()
            : base("name=empinterviewEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<TblDept> TblDepts { get; set; }
        public virtual DbSet<TblDsg> TblDsgs { get; set; }
        public virtual DbSet<TblEmp> TblEmps { get; set; }
    }
}
