//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInterview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDept
    {
        public TblDept()
        {
            this.TblEmps = new HashSet<TblEmp>();
        }
        public int Id { get; set; }
        public string Dept { get; set; }

        public virtual ICollection<TblEmp> TblEmps { get; set; }
    }
}
