//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpInterview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmp
    {
        public int Sr_No_ { get; set; }
        public string Name { get; set; }
        public Nullable<int> Dsg { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<decimal> Salary { get; set; }

        public virtual TblDsg TblDsg { get; set; }
        public virtual TblDept TblDept { get; set; }
        public virtual Gender Gender1{ get; set; }
    }
}
